### DISCUSSION TITLE
Support to have an eventual phase that can be run at the end of every action

### DISCUSSION THREAD

**Discussion by viveksinghggits** [kanisterio/kanister#1220] [Ideas]
@glothriel, was kind enough give this feedback to have an eventual phase for every action to make sure we are able to cleanup the resources if they were created in previous phases.
I am creating this thread to continue the discussion and if you have any other ideas around it and then we can add this to the roadmap.

- [ ] Eventual phase should be called after all the phases of an action are called
- [ ] It should be called irrespective of the status of previous phases

**Comment by viveksinghggits** [comment]
Hi @pavannd1 @ihcsim 
Instead of having a field `AlwaysRun` in the [type BlueprintPhase](https://github.com/kanisterio/kanister/blob/master/pkg/apis/cr/v1alpha1/types.go#L200), I was thinking of having a field called `EventualPhase` in the `BlueprintAction` struct. Something like this

```
type BlueprintAction struct {
	Name               string              `json:"name"`
	Kind               string              `json:"kind"`
	ConfigMapNames     []string            `json:"configMapNames,omitempty"`
	SecretNames        []string            `json:"secretNames,omitempty"`
	InputArtifactNames []string            `json:"inputArtifactNames,omitempty"`
	OutputArtifacts    map[string]Artifact `json:"outputArtifacts,omitempty"`
	Phases             []BlueprintPhase    `json:"phases,omitempty"`
        EventualPhase BlueprintPhase    `json:"eventualPhase,omitempty"`
}
```
Having the eventual phse this way won't require any additional logic to make sure that eventual phase is actually running at the very end. Otherwise if we include a field in `BlueprintPhase` type we will have to make sure that we are running that phase after every other phase for that action is completed (success/failure).
what do you think about this.

**Reply by ihcsim** [reply]
What happens if eventual phase failed, but all previous phases succeeded? Do we fail the action even though the eventual phase may not necessary be part of the "core" phases?

**Reply by pavannd1** [reply]
I think this adds more overhead on blueprint authors. Yes, it would make the controller logic simple but would make blueprints complex. Before going deeper into designing this, can we find all the use cases where this is required?

One of the cases I can think of is quiescing and un-quiescing a database while running backup/restore phases. We would want to un-quiesce the database regardless of backup/restore results.
The reason I suggested a boolean field in the phase is that for the above example - we would have 3 phases in the blueprint where the last phase is marked as `AlwaysRun` whereas, in this design, we would be adding 2 phases in the "core" `Phases` list and then add a new phase under `EventualPhase`. Although the quiesce and un-quiesce phases are related, they are now in different fields.

Another alternative is to provide well-known `actions` called `pre-hook` and `post-hook` where a `post-hook` action is always run after the preceding `action` regardless of its status.

**Reply by ihcsim** [reply]
Basically, I think the handling of `EventualPhase` should be different from that of a `Phase`. I like the idea of `pre-hook` and `post-hook` phases (assuming backup and restore are represented as actions), to allow us to implement different error handling mechanisms. For example:

```yaml
actions:
  backup:
    phases:
    - func: KubeExec
      name: dump-db
    - func: KubeExec
      name: upload-to-s3
    pre:     # if failed, do not execute "core" or "main" phases
    - func: KubeExec
      name: flush-and-lock-tables
    post:    # always execute regardless of returned values of "core" phases
             # if failed, issue a warning
    - func: KubeExec
      name: unlock-tables
    - func: KubeExec
      name: cleanup
  retore:
    phases:
    - func: KubeExec
      name: restore-db-in-recovery-mode
    pre:     # if failed, do not execute "core" or "main" phases
    - func: KubeExec
      name: download-from-s3
    post:    # always execute regardless of returned values of "core" phases
             # if failed, issue a warning
    - func: KubeExec
      name: rollback-if-failed
```

**Reply by pavannd1** [reply]
Ah yes! Hook phases sound better than hook actions 👍🏼

**Reply by viveksinghggits** [reply]
this looks good. thanks @ihcsim . I will start the implementation soon.

**Reply by viveksinghggits** [reply]
should we close the discussion.

**Reply by ihcsim** [reply]
Maybe convert it to an issue.

**Reply by viveksinghggits** [reply]
right, but I don't see any option to close the discussion. Let's see.

**Reply by viveksinghggits** [reply]
Hi @ihcsim 
do you think we that type of `pre` and `post` should be `[]BlueprintPhase` or it should just be `BlueprintPhase`. Also how does `preHook` and `postHook` sound instead of `pre` and `post`.

**Reply by viveksinghggits** [reply]
also, the other thing that I observed is there is no need to introduce `preHook`. The thing that we are trying to achieve using `preHook` can easily be achieved  using phases of a function.

**Reply by ihcsim** [reply]
I am hesitant to call them hooks because hooks are usually event-driven. In our case, we want a way to order the phases, ensure that they are always run, and their errors are handled differently.

I don't see why we can't use `[]BlueprintPhase`. Are you aware of any issues? 

Do we have any mechanism to mark this feature as experimental (at least in the docs), indicating that we might rename, deprecate, redesign it in subsequent releases?

**Reply by viveksinghggits** [reply]
Hi @ihcsim 
>  In our case, we want a way to order the phases, ensure that they are always run, and their errors are handled differently.

this can be achieved today by just having phases in actions. And that is the reason I don't want to have preHook because, in that case we are basically having two ways to do the exact same thing which I want to avoid.

I don't think we have any issues with having `[]BlueprintPhase` as type. We can do that.
We have not marked features as experimental before but if there is a need we can do that, I think.

**Reply by pavannd1** [reply]
I think we should have both `pre` and `post` for consistency and maybe add enough documentation to educate authors on the use of `pre` vs just having a phase in `phases`.

**Reply by viveksinghggits** [reply]
Continuing in another comment this is getting too lengthy.

**Comment by viveksinghggits** [comment]
> I think we should have both pre and post for consistency and maybe add enough documentation to educate authors on the use of pre vs just having a phase in phases.

I somehow still think that we don't need pre hook because of below reasons
- We will have to put extra efforts in docs to specify how to use hooks
- Since same thing can be achieved by two ways, we are making things confusing

I also don't think we have specified or used pre hooks like this before (in other blueprints) and changing that is going to be problem with consistency. What do you think @pavannd1 @ihcsim .

**Comment by mandreasik** [comment]
Hi guys :) 

I was asked by @glothriel to prepare short summary based on our use cases of blueprints. So let's get started

**use case based on our "restore" action:**

_note:_
custom operator takes care of creating custom database, users etc on db cluster

1. scale custom operator down (we don't want any unpredictable actions to be taken on database when performing restore)
2. restore mysql database (whole server or particular database)
3. scale custom operator up

If restore of database will fail due to any reason our custom operator is not running which means that part of our application is not working correctly, and we need to manually restore scale of our custom operator

**use case based on our "backup" action:**
Right now kanister does not support backup rotation, post actions like "cleanup" or cleaning up failed actionsets (eg. preserving only last two recent or so) so we had to code it by ourselves. We did it by adding second phase to "backup" action.

Having this in mind all our backup actions in blueprint look like:
1. prepare data (ew. mount some volumes) and perform backup to remote storage using restic
2. "rotate backup"
	* run restic cleanup - in case previous actionset failed and we have data block not connected to particular restic snapshot
	* run restic backup rotation
	* cleanup failed actionsets preserving only last two recently failed

So if backup phase will fail, we are left with: failed actionsets (that are potentially piling up) and potential unused trash data inside restic repository.

Of course next successful backup would fix this issue but what if there is a bug and backup is failing few times? this could lead to more trash data inside restic repo.

Having special "finally" phase that would fire, regardless backup failed or not would fix above case

**Reply by viveksinghggits** [reply]
Hi @mandreasik,
thanks for the comment, we have started implementing this and this is how the blueprint should look like
```
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: mysql-blueprint
actions:
  backup:
    phases:
    - func: KubeTask
      name: phaseOne
      args:
        image: ghcr.io/kanisterio/mysql-sidecar:0.74.0
        namespace: "{{ .StatefulSet.Namespace }}"
        command:
    - func: KubeTask
      name: phaseTwo
      args:
        image: ghcr.io/kanisterio/mysql-sidecar:0.74.0
        namespace: "{{ .StatefulSet.Namespace }}"
        command:
    - func: KubeTask
      name: phaseThree
      args:
        image: ghcr.io/kanisterio/mysql-sidecar:0.74.0
        namespace: "{{ .StatefulSet.Namespace }}"
        command:
    deferPhase:
      func: KubeTask
      name: finalPhase
      args:
        image: ghcr.io/kanisterio/mysql-sidecar:0.74.0
        namespace: "{{ .StatefulSet.Namespace }}"
        command:
```

as you can assume by looking at this blueprint, `deferPhase` going to run eventually irrespective of the status of the main phases that are specified in the blueprint. Please let us know what do you think. 
Sorry for the delay in response.
