### ISSUE TITLE
[BUG] Failed to create snapshot with "CreateCSISnapshot" just after deleting it with "DeleteCSISnapshot"

### ISSUE THREAD

**Issue by muffl0n** [kanisterio/kanister#1202]
**Describe the bug**
I have a blueprint where I delete a CSISnapshot and recreate it in the next step. The delete finishes successfully, but the creation fails afterwards:
```
time="2022-01-24T07:31:43.425210918Z" level=info msg="Executing action backup" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction" Line=379 cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:43.465776946Z" level=info msg="Created actionset and started executing actions" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onAddActionSet" Line=208 NewActionSetName=staging-server-cd7vw cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:43.465944444Z" level=info msg="Executing phase ShutdownPod" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1" Line=401 Phase=ShutdownPod cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:43.465908243Z" level=info msg="Updated ActionSet" Actionset=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet" Line=227 Status=pending cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:43.466164877Z" level=info msg="Updated ActionSet" Actionset=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet" Line=234 Phase="ShutdownPod->pending" Status=running cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.328111219Z" level=info msg="Updated ActionSet" Actionset=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet" Line=234 Phase="deleteCSISnapshot->pending" Status=running cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.328330998Z" level=info msg="Completed phase ShutdownPod" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1" Line=442 Phase=ShutdownPod cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.328426477Z" level=info msg="Executing phase deleteCSISnapshot" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1" Line=401 Phase=deleteCSISnapshot cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.362828547Z" level=info msg="Updated ActionSet" Actionset=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet" Line=234 Phase="createCSISnapshot->pending" Status=running cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.363458259Z" level=info msg="Completed phase deleteCSISnapshot" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1" Line=442 Phase=deleteCSISnapshot cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.363575971Z" level=info msg="Executing phase createCSISnapshot" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1" Line=401 Phase=createCSISnapshot cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.396160693Z" level=info msg="Updated ActionSet" Actionset=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet" Line=227 Status=failed cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf hostname=kanister-kanister-operator-789fd58966-mhxbl
time="2022-01-24T07:31:56.396171791Z" level=info msg="Failed to execute phase: v1alpha1.Phase{Name:\"createCSISnapshot\", State:\"pending\", Output:map[string]interface {}(nil)}:" ActionSet=staging-server-cd7vw File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1" Line=438 Phase=createCSISnapshot cluster_name=684f75d4-1734-4ec3-84b2-a56c001e71cf error="Failed to create snapshot resource foobar-server-storage-staging-backup-latest, Namespace foobar: object is being deleted: volumesnapshots.snapshot.storage.k8s.io \"foobar-server-storage-staging-backup-latest\" already exists" hostname=kanister-kanister-operator-789fd58966-mhxbl

```

**To Reproduce**
1. Create blueprint: 
```
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: staging-server
actions:
  backup:
    phases:
      - func: ScaleWorkload
        name: ShutdownPod
        args:
          namespace: "foobar"
          name: "staging-backup-foobar-server"
          kind: statefulset
          replicas: 0
      - func: DeleteCSISnapshot
        name: deleteCSISnapshot
        args:
          namespace: "foobar"
          name: "foobar-server-storage-staging-backup-latest"
      - func: CreateCSISnapshot
        name: createCSISnapshot
        args:
          namespace: "foobar"
          pvc: "foobar-server-storage-staging-backup-foobar-server-0"
          name: "foobar-server-storage-staging-backup-latest"
          snapshotClass: default-snapshot
      - func: ScaleWorkload
        name: ScalePodUp
        args:
          namespace: "foobar"
          name: "staging-backup-foobar-server"
          kind: statefulset
          replicas: 1

```
2. Create ActionSet to run the backup
```
apiVersion: cr.kanister.io/v1alpha1
kind: ActionSet
metadata:
  generateName: staging-server-
  namespace: kanister
spec:
  actions:
    - name: backup
      blueprint: staging-server
      object:
        kind: StatefulSet
        name: staging-foobar-server
        namespace: foobar
```

**Expected behavior**
1. Workload is scaled down
2. CSISnapshot is deleted
3. CSISnapshot is created
4. Workload is scaled up

**Observed behavior**
1. Workload is scaled down
2. CSISnapshot is deleted (sort of...)
3. CSISnapshot can't be created, cause old Snapshot is still present. Though phase "deleteCSISnapshot" completed successfully 

**Environment**
Kubernetes Version/Provider: GKE v1.21.5-gke.1802
Storage Provider: GCS
Cluster Size (#nodes): 4
Data Size: ~500MB

**Additional context**
I'm using kanisterio/controller:v9.99.9-dev (1fd1ce72) cause function "DeleteCSISnapshot" is not yet relased.
I found a workaround to give the deletion of the snapshot more time to complete. I changed the order of the steps to:
1. CSISnapshot is deleted
2. Workload is scaled down
3. CSISnapshot is created
4. Workload is scaled up

That *does* work, but extends the time, where the snapshot is not available.
