### ISSUE TITLE
[BUG] argument imagePullPolicy is not supported

### ISSUE THREAD

**Issue by muffl0n** [kanisterio/kanister#1288]
**Describe the bug**
I built a docker image of branch "preprovision-snapshot". Now when I use the function "KubeTask" like this
```
      - func: KubeTask
        name: getImageUpdateServiceReplicaCount
        args:
          image: "myimage:latest"
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -ce
            - |
              doSth()
```
I get this error message
```
Warning  ActionSetFailed Action: restore  29s   Kanister Controller  Failed to execute phase: v1alpha1.Phase{Name:"getImageUpdateServiceReplicaCount", State:"pending", Output:map[string]interface {}(nil)}: Checking supported args for function KubeTask.: argument imagePullPolicy is not supported
```

**To Reproduce**
1. Install kanister operator with image ghcr.io/muffl0n/kanisterio/controller:v9.99.9-dev-snapshots
2. Run blueprint with above function

**Expected behavior**
I'd expect the function to pull the image and run the container.
