### ISSUE TITLE
`DeferPhase` is not being validated via blueprint validating webhook  

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1360]
So far this is working more or less as expected :+1:. One thing I notice is that it doesn't look like the validating webhook is checking the `deferPhase`. Can you confirm?

I tested with the following YAML:

```yaml
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: scale
  namespace: kanister
actions:
  scale:
    phases:
    - func: ScaleWorkload
      name: scale-down
      args:
        namespace: default
        name: nginx
        kind: deployment
        replicas: 0
    - func: ScaleWorkload
      name: error
      args:
        namespace: default
        name: non-existent
        kind: deployment
        replicas: 10
    deferPhase:
      func: ScaleWorkload
      name: scale-up
      args:
        namespace: default
        name: nginx
        kind: deployment
        replicas: 3
---
apiVersion: cr.kanister.io/v1alpha1
kind: ActionSet
metadata:
  generateName: scale-
  namespace: kanister
spec:
  actions:
  - name: scale
    blueprint: scale
    object:
      kind: Namespace
      name: default
```
When I had an invalid key in the `args` of the `deferPhase`, the validating webhook didn't seem to catch it.

_Originally posted by @ihcsim in https://github.com/kanisterio/kanister/issues/1297#issuecomment-1089795269_
