### ISSUE TITLE
Add support to patch resources in KubeOps function

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#1363]
**Is your feature request related to a problem? Please describe.**

Currently, [KubeOps](https://docs.kanister.io/functions.html#kubeops) function supports `create` and `delete` operations. It would be useful to add support to patch resources through KubeOps function. Sample use cases are - e.g the places where we want to add labels or annotations as a part of backup operations

**Describe the solution you'd like**

Sample BP specs:

```
- func: KubeOps
  name: patchResource
  args:
    operation: patch
    objectReference:
      apiVersion: ""
      group: ""
      kind: ""
      name: ""
      namespace: ""
      resource: ""
    patch: |                              # yaml/json patch
      spec:
        replicas: 3
```

**Describe alternatives you've considered**

As of now, this can be achieved by running shell commands (kubectl patch) with kubeops function.
