### ISSUE TITLE
[BUG] RestoreCSISnapshot inputArtifacts not working properly

### ISSUE THREAD

**Issue by mich-jh** [kanisterio/kanister#1383]
**Describe the bug**
When trying to use the CreateCSISnapshot and RestoreCSISnapshot functions, the inputArtifact is not rendered properly in the yaml causing a `Failed to execute phase: v1alpha1.Phase{Name:"restoreCSISnapshot", State:"pending", Output:map[string]interface {}(nil)}: Failed to render template: "snapshotInfo" not found` issue.

**To Reproduce**
1. Created a blueprint yaml file as following

``` apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: single-node-test
  namespace: kanister
actions:
  backup:
    outputArtifacts:
      snapshotInfo:
        keyValue:
          name: "{{ .Phases.createCSISnapshotZookeeper.Output.name }}"
          pvc: "{{ .Phases.createCSISnapshotZookeeper.Output.pvc }}"
          namespace: "{{ .Phases.createCSISnapshotZookeeper.Output.namespace }}"
          restoreSize: "{{ .Phases.createCSISnapshotZookeeper.Output.restoreSize }}"
          snapshotContent: "{{ .Phases.createCSISnapshotZookeeper.Output.snapshotContent }}"
    phases:
    - func: CreateCSISnapshot
      name: createCSISnapshotZookeeper
      args:
        pvc: "storage-{{ .Object.metadata.name }}-zookeeper-0-0"
        namespace: kanister
        snapshotClass: csi-aws-vsc
  restore:
    inputArtifactNames:
    - snapshotInfo
    phases:
    - func: RestoreCSISnapshot
      name: restoreCSISnapshotDataServer
      args:
        name: "{{ .ArtifactsIn.snapshotInfo.KeyValue.name }}"
        pvc: "{{ .ArtifactsIn.snapshotInfo.KeyValue.pvc }}"
        namespace: "{{ .ArtifactsIn.snapshotInfo.KeyValue.namespace }}"
        storageClass: ebs-sc
        restoreSize: "{{ .ArtifactsIn.snapshotInfo.KeyValue.restoreSize }}"
        accessModes: ["ReadWriteOnce"]
        volumeMode: "Filesystem" 
``` 

When applying the actionset, the RestoreCSISnapshot function fails with a `Failed to execute phase: v1alpha1.Phase{Name:"restoreCSISnapshotDataServer", State:"pending", Output:map[string]interface {}(nil)}: Failed to render template: "snapshotInfo" not found` error. 

It is not an issue with the system/setup as hardcoding the names of the snapshots in the restore args works fine. 

**Expected behavior**
Expecting the RestoreCSISnapshot to pass 

**Environment**
Kubernetes Version/Provider: v1.21.5-eks-bc4871b
Storage Provider: AWS
Cluster Size (#nodes): 6
Data Size: NA

**Additional context**
The real blueprint I am trying to test is 
```
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: single-node
  namespace: kanister
actions:
  backup:
    outputArtifacts:
      backupDataServerInfo:
        keyValue:
          name: "{{ .Phases.createCSISnapshotDataServer.Output.name }}"
          pvc: "{{ .Phases.createCSISnapshotDataServer.Output.pvc }}"
          namespace: "{{ .Phases.createCSISnapshotDataServer.Output.namespace }}"
          restoreSize: "{{ .Phases.createCSISnapshotDataServer.Output.restoreSize }}"
          snapshotContent: "{{ .Phases.createCSISnapshotDataServer.Output.snapshotContent }}"
      backupKafkaInfo:
        keyValue:
          name: "{{ .Phases.createCSISnapshotKafka.Output.name }}"
          pvc: "{{ .Phases.createCSISnapshotKafka.Output.pvc }}"
          namespace: "{{ .Phases.createCSISnapshotKafka.Output.namespace }}"
          restoreSize: "{{ .Phases.createCSISnapshotKafka.Output.restoreSize }}"
          snapshotContent: "{{ .Phases.createCSISnapshotKafka.Output.snapshotContent }}"
      backupSearchServerInfo:
        keyValue:
          name: "{{ .Phases.createCSISnapshotSearchServer.Output.name }}"
          pvc: "{{ .Phases.createCSISnapshotSearchServer.Output.pvc }}"
          namespace: "{{ .Phases.createCSISnapshotSearchServer.Output.namespace }}"
          restoreSize: "{{ .Phases.createCSISnapshotSearchServer.Output.restoreSize }}"
          snapshotContent: "{{ .Phases.createCSISnapshotSearchServer.Output.snapshotContent }}"
      backupServiceManagerInfo:
        keyValue:
          name: "{{ .Phases.createCSISnapshotServiceManager.Output.name }}"
          pvc: "{{ .Phases.createCSISnapshotServiceManager.Output.pvc }}"
          namespace: "{{ .Phases.createCSISnapshotServiceManager.Output.namespace }}"
          restoreSize: "{{ .Phases.createCSISnapshotServiceManager.Output.restoreSize }}"
          snapshotContent: "{{ .Phases.createCSISnapshotServiceManager.Output.snapshotContent }}"
      backupWebappInfo:
        keyValue:
          name: "{{ .Phases.createCSISnapshotWebapp.Output.name }}"
          pvc: "{{ .Phases.createCSISnapshotWebapp.Output.pvc }}"
          namespace: "{{ .Phases.createCSISnapshotWebapp.Output.namespace }}"
          restoreSize: "{{ .Phases.createCSISnapshotWebapp.Output.restoreSize }}"
          snapshotContent: "{{ .Phases.createCSISnapshotWebapp.Output.snapshotContent }}"
      backupZookeeperInfo:
        keyValue:
          name: "{{ .Phases.createCSISnapshotZookeeper.Output.name }}"
          pvc: "{{ .Phases.createCSISnapshotZookeeper.Output.pvc }}"
          namespace: "{{ .Phases.createCSISnapshotZookeeper.Output.namespace }}"
          restoreSize: "{{ .Phases.createCSISnapshotZookeeper.Output.restoreSize }}"
          snapshotContent: "{{ .Phases.createCSISnapshotZookeeper.Output.snapshotContent }}"
    phases:
    - name: freeze-zookeeper
      func: KubeExec
      args:
        namespace: "{{ .Object.metadata.namespace }}"
        pod: "{{ .Object.metadata.name }}-zookeeper-0-0"
        container: fsfreeze
        command:
          - /bin/fsfreeze
          - --freeze
          - /storage
    - name: freeze-kafka
      func: KubeExec
      args:
        namespace: "{{ .Object.metadata.namespace }}"
        pod: "{{ .Object.metadata.name }}-kafka-0-0"
        container: "fsfreeze"
        command:
          - /bin/fsfreeze
          - --freeze
          - /storage
    - name: freeze-service-manager
      func: KubeExec
      args:
        namespace: "{{ .Object.metadata.namespace }}"
        pod: "{{ .Object.metadata.name }}-service-manager-0-0"
        container: "fsfreeze"
        command:
          - /bin/fsfreeze
          - --freeze
          - /storage
    - name: freeze-data-server
      func: KubeExec
      args:
        namespace: "{{ .Object.metadata.namespace }}"
        pod: "{{ .Object.metadata.name }}-data-server-0-0"
        container: "fsfreeze"
        command:
          - /bin/fsfreeze
          - --freeze
          - /storage
    - name: freeze-search-server
      func: KubeExec
      args:
        namespace: "{{ .Object.metadata.namespace }}"
        pod: "{{ .Object.metadata.name }}-search-server-0-0"
        container: "fsfreeze"
        command:
          - /bin/fsfreeze
          - --freeze
          - /storage
    - name: freeze-webapp
      func: KubeExec
      args:
        namespace: "{{ .Object.metadata.namespace }}"
        pod: "{{ .Object.metadata.name }}-webapp-0-0"
        container: "fsfreeze"
        command:
          - /bin/fsfreeze
          - --freeze
          - /storage
    - func: CreateCSISnapshot
      name: createCSISnapshotDataServer
      args:
        pvc: "storage-{{ .Object.metadata.name }}-data-server-0-0"
        namespace: kanister
        snapshotClass: csi-aws-vsc
    - func: CreateCSISnapshot
      name: createCSISnapshotKafka
      args:
        pvc: "storage-{{ .Object.metadata.name }}-kafka-0-0"
        namespace: kanister
        snapshotClass: csi-aws-vsc
    - func: CreateCSISnapshot
      name: createCSISnapshotSearchServer
      args:
        pvc: "storage-{{ .Object.metadata.name }}-search-server-0-0"
        namespace: kanister
        snapshotClass: csi-aws-vsc
    - func: CreateCSISnapshot
      name: createCSISnapshotServiceManager
      args:
        pvc: "storage-{{ .Object.metadata.name }}-service-manager-0-0"
        namespace: kanister
        snapshotClass: csi-aws-vsc
    - func: CreateCSISnapshot
      name: createCSISnapshotWebapp
      args:
        pvc: "storage-{{ .Object.metadata.name }}-webapp-0-0"
        namespace: kanister
        snapshotClass: csi-aws-vsc
    - func: CreateCSISnapshot
      name: createCSISnapshotZookeeper
      args:
        pvc: "storage-{{ .Object.metadata.name }}-zookeeper-0-0"
        namespace: kanister
        snapshotClass: csi-aws-vsc
  restore:
    inputArtifactNames:
    - backupDataServerInfo
    - backupKafkaInfo
    - backupSearchServerInfo
    - backupServiceManagerInfo
    - backupWebappInfo
    - backupZookeeperInfo
    phases:
      - func: RestoreCSISnapshot
        name: restoreCSISnapshotDataServer
        args:
          name: "{{ .ArtifactsIn.backupDataServerInfo.KeyValue.name }}"
          pvc: "{{ .ArtifactsIn.backupDataServerInfo.KeyValue.pvc }}-restored"
          namespace: "{{ .ArtifactsIn.backupDataServerInfo.KeyValue.namespace }}"
          storageClass: ebs-sc
          restoreSize: "{{ .ArtifactsIn.backupDataServerInfo.KeyValue.restoreSize }}"
          accessModes: ["ReadWriteOnce"]
          volumeMode: "Filesystem"
      - func: RestoreCSISnapshot
        name: restoreCSISnapshotKafka
        args:
          name: "{{ .ArtifactsIn.backupKafkaInfo.KeyValue.name }}"
          pvc: "{{ .ArtifactsIn.backupKafkaInfo.KeyValue.pvc }}-restored"
          namespace: "{{ .ArtifactsIn.backupKafkaInfo.KeyValue.namespace }}"
          storageClass: ebs-sc
          restoreSize: "{{ .ArtifactsIn.backupKafkaInfo.KeyValue.restoreSize }}"
          accessModes: ["ReadWriteOnce"]
          volumeMode: "Filesystem"
      - func: RestoreCSISnapshot
        name: restoreCSISnapshotSearchServer
        args:
          name: "{{ .ArtifactsIn.backupSearchServerInfo.KeyValue.name }}"
          pvc: "{{ .ArtifactsIn.backupSearchServerInfo.KeyValue.pvc }}-restored"
          namespace: "{{ .ArtifactsIn.backupSearchServerInfo.KeyValue.namespace }}"
          storageClass: ebs-sc
          restoreSize: "{{ .ArtifactsIn.backupSearchServerInfo.KeyValue.restoreSize }}"
          accessModes: ["ReadWriteOnce"]
          volumeMode: "Filesystem"
      - func: RestoreCSISnapshot
        name: restoreCSISnapshotServiceManager
        args:
          name: "{{ .ArtifactsIn.backupServiceManagerInfo.KeyValue.name }}"
          pvc: "{{ .ArtifactsIn.backupServiceManagerInfo.KeyValue.pvc }}-restored"
          namespace: "{{ .ArtifactsIn.backupServiceManagerInfo.KeyValue.namespace }}"
          storageClass: ebs-sc
          restoreSize: "{{ .ArtifactsIn.backupServiceManagerInfo.KeyValue.restoreSize }}"
          accessModes: ["ReadWriteOnce"]
          volumeMode: "Filesystem"
      - func: RestoreCSISnapshot
        name: restoreCSISnapshotWebapp
        args:
          name: "{{ .ArtifactsIn.backupWebappInfo.KeyValue.name }}"
          pvc: "{{ .ArtifactsIn.backupWebappInfo.KeyValue.pvc }}-restored"
          namespace: "{{ .ArtifactsIn.backupWebappInfo.KeyValue.namespace }}"
          storageClass: ebs-sc
          restoreSize: "{{ .ArtifactsIn.backupWebappInfo.KeyValue.restoreSize }}"
          accessModes: ["ReadWriteOnce"]
          volumeMode: "Filesystem"
      - func: RestoreCSISnapshot
        name: restoreCSISnapshotZookeeper
        args:
          name: "{{ .ArtifactsIn.backupZookeeperInfo.KeyValue.name }}"
          pvc: "{{ .ArtifactsIn.backupZookeeperInfo.KeyValue.pvc }}-restored"
          namespace: "{{ .ArtifactsIn.backupZookeeperInfo.KeyValue.namespace }}"
          storageClass: ebs-sc
          restoreSize: "{{ .ArtifactsIn.backupZookeeperInfo.KeyValue.restoreSize }}"
          accessModes: ["ReadWriteOnce"]
          volumeMode: "Filesystem"
      - name: unfreeze-zookeeper
        func: KubeExec
        args:
          namespace: "{{ .Object.metadata.namespace }}"
          pod: "{{ .Object.metadata.name }}-zookeeper-0-0"
          container: fsfreeze
          command:
            - /bin/fsfreeze
            - --unfreeze
            - /storage
      - name: unfreeze-kafka
        func: KubeExec
        args:
          namespace: "{{ .Object.metadata.namespace }}"
          pod: "{{ .Object.metadata.name }}-kafka-0-0"
          container: "fsfreeze"
          command:
            - /bin/fsfreeze
            - --unfreeze
            - /storage
      - name: unfreeze-service-manager
        func: KubeExec
        args:
          namespace: "{{ .Object.metadata.namespace }}"
          pod: "{{ .Object.metadata.name }}-service-manager-0-0"
          container: "fsfreeze"
          command:
            - /bin/fsfreeze
            - --unfreeze
            - /storage
      - name: unfreeze-data-server
        func: KubeExec
        args:
          namespace: "{{ .Object.metadata.namespace }}"
          pod: "{{ .Object.metadata.name }}-data-server-0-0"
          container: "fsfreeze"
          command:
            - /bin/fsfreeze
            - --unfreeze
            - /storage
      - name: unfreeze-search-server
        func: KubeExec
        args:
          namespace: "{{ .Object.metadata.namespace }}"
          pod: "{{ .Object.metadata.name }}-search-server-0-0"
          container: "fsfreeze"
          command:
            - /bin/fsfreeze
            - --unfreeze
            - /storage
      - name: unfreeze-webapp
        func: KubeExec
        args:
          namespace: "{{ .Object.metadata.namespace }}"
          pod: "{{ .Object.metadata.name }}-webapp-0-0"
          container: "fsfreeze"
          command:
            - /bin/fsfreeze
            - --unfreeze
            - /storage
```
This fails with the same error as above. The first blueprint listed is a simplified version of my desired blueprint with one input/output artifact.
