### ISSUE TITLE
Extend Artifacts Template Parameter To Support List And Map Values

### ISSUE THREAD

**Issue by ihcsim** [kanisterio/kanister#1385]
**Is your feature request related to a problem? Please describe.**

The [`Artifacts`](https://docs.kanister.io/templates.html#artifacts) template parameter only works with the `KeyValue` map (of string to string). I wonder if we can change it into a map of string to `interface{}` so that we can support cases like:

```yaml
actions:
    createSnapshot
      phases:
      - func: CreateCSISnapshot
        name: createSnapshot
        args:
          accessModes: {{ .ArtifactsIn.pvc.KeyValue.accessModes }} # a list
          labels: {{ .ArtifactsIn.pvc.KeyValue.labels }} # a map
```

The JSON marshaling/unmarshaling seems possible per example at https://go.dev/play/p/_x8MAl2KoSq

**Describe the solution you'd like**

Be able to define lists and maps in my action set's input artifacts, and passed them into my blueprint. This will let me keep my blueprint DRY, while allowing me to pass in custom inputs from my action sets.

**Describe alternatives you've considered**

In the action set, explicitly define all the key/value pairs needed by my list or map. This requires me to hardcode the expected number of items in the list or map in my blueprint.
