### ISSUE TITLE
Template does not evaluate as expected in the pods field of KubeExecAll

### ISSUE THREAD

**Issue by michaelcourcy** [kanisterio/kanister#1470]
**Describe the bug**
pods field in KubeExecAll can be go-templated. Despite my template is correct given the postgresql object I pass to the action set Kanister can't interpret it.

```
pods: "{{range until (int .Object.spec.numberOfInstances)}} {{ $.Object.metadata.name }}-{{.}}{{end}}"
```

generate this error message 
```
 error:
    message: |-
      pods ".Object.spec.numberOfInstances)}}" not found
      pods "until" not found
      pods "}}-{{.}}{{end}}" not found
      pods "{{range" not found
      pods "$.Object.metadata.name" not found
      pods "(int" not found
      pods "{{" not found
  state: failed
```

For instance this template 
```
pods: '{{range until 3}} acid-pg-cluster-{{.}}{{end}}'
```
or  this one 
```
pods: "{{ .Object.metadata.name }}-0 {{ .Object.metadata.name }}-1 {{ .Object.metadata.name }}-2"
```
 work fine.

I also check the validity of this template with this go code 
```
package main

import (
	"fmt"
	"os"
	"text/template"

	"github.com/Masterminds/sprig"
)

func main() {

	// Set up variables and template.
	numberOfInstances := int64(3)
	vars := map[string]interface{}{
		"Object": map[string]interface{}{
			"metadata": map[string]interface{}{"name": "acid-pg-cluster"},
			"spec":     map[string]interface{}{"numberOfInstances": numberOfInstances}}}
	tpl := `{{range until (int .Object.spec.numberOfInstances)}} {{ $.Object.metadata.name }}-{{.}}{{end}}`

	// Get the Sprig function map.
	fmap := sprig.TxtFuncMap()
	t := template.Must(template.New("test").Funcs(fmap).Parse(tpl))

	err := t.Execute(os.Stdout, vars)
	if err != nil {
		fmt.Printf("Error during template execution: %s", err)
		return
	}

}
```

**To Reproduce**

Install zalando operator and a postgresql example 
```
helm repo add postgres-operator-charts https://opensource.zalando.com/postgres-operator/charts/postgres-operator
helm install postgres-operator postgres-operator-charts/postgres-operator
cat <<EOF | kubectl create -f -
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-pg-cluster
  namespace: "default"
  labels:
    team: acid
spec:
  teamId: "acid"
  volume:
    size: "200Gi"
  numberOfInstances: 3
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  allowedSourceRanges:  # load balancers' source ranges for both master and replica services
  - 127.0.0.1/32
  postgresql:
    version: "13"
    parameters: # Expert section
      shared_buffers: "500MB"
      effective_cache_size: "1500MB"
      max_connections: "300" #setting this based on mariadb (cmdb)
      log_statement: "ddl"
      wal_compression: "on"
      work_mem: "40MB"
      random_page_cost: "1.0"
      autovacuum_vacuum_scale_factor: "0.1"
      logging_collector: "off"
      log_destination: "stderr"
      shared_preload_libraries: "pgaudit,pg_stat_statements,pg_stat_kcache"
      wal_keep_size: "1024MB"
  enableShmVolume: false
  # podPriorityClassName: "nom-backend-service-db"
  spiloRunAsUser: 101
  spiloFSGroup: 103
  resources:
    requests:
      cpu: "1000m"
      memory: "1500Mi"
    limits:
      cpu: "2000m"
      memory: "1500Mi"
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    #pg_hba, please note: whole pg_hba.conf gets overwritten.
    ttl: 30
    loop_wait: &loop_wait 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: true
    maximum_lag_on_failover: 33554432    
  serviceAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
EOF
```

Wait for the acid-pg-cluster to be ready then install this blueprint 
```
cat <<EOF | kubectl create -f -
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata: 
  name: zalando-bp-simplified
  namespace: kasten-io  
actions:
  helloZalando:
    phases:    
    - func: KubeExecAll
      name: helloToAllPods      
      args:
        namespace: "{{ .Object.metadata.namespace }}"
        # work
        #pods: '{{range until 3}} acid-pg-cluster-{{.}}{{end}}'
        # does not work we're investigating
        pods: "{{range until (int .Object.spec.numberOfInstances)}} {{ $.Object.metadata.name }}-{{.}}{{end}}"
        # work
        #pods: "{{ .Object.metadata.name }}-0 {{ .Object.metadata.name }}-1 {{ .Object.metadata.name }}-2"
        containers: postgres
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
           touch helloZalando.txt            
EOF
```

And execute the actionset  
```
cat <<EOF | kubectl create -f -
apiVersion: cr.kanister.io/v1alpha1
kind: ActionSet
metadata:  
  name: hello-zalando-actionset
  namespace: kasten-io  
spec:
  actions:
  - blueprint: zalando-bp-simplified
    name: helloZalando
    object:
      apiVersion: v1
      group: acid.zalan.do
      kind: ""
      name: acid-pg-cluster
      namespace: default
      resource: postgresqls
    preferredVersion: v1.0.0-alpha
    profile:
      apiVersion: v1alpha1
      group: ""
      kind: profile
      name: kanister-phase-k10-location-k7f9x
      namespace: kasten-io
      resource: ""
EOF
```

**Expected behavior**
Actionset should complete but get the error described above

**Environment**
Kubernetes Version/Provider: 
```
k version 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c66c03f3012a10f16eb86fdce6330433adf6c9ee", GitTreeState:"clean", BuildDate:"2021-03-13T02:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
Storage Provider: azure
Cluster Size (#nodes): 3
Data Size: 200Gi 
kasten version : 4.5.14

**Comment by michaelcourcy** [comment]
I see, yes that would make the blueprint more portable. Advanced blueprint want to leverage full templating. at least me :)

**Comment by ihcsim** [comment]
Yeah, I agreed with re-usable and portable blueprints. We will need to look deeper into how the context is interpreted in our code. If you have some bandwidth, we can use some help there. AFAICT, that part of the code base hasn't changed for a while.

**Comment by michaelcourcy** [comment]
I can try.

**Comment by ihcsim** [comment]
Looks like the issue is that our renderer is confused by the `$.` prefix, thinking that it's a jsonpath instead of a reference to the global Helm scope. The [current code](https://github.com/kanisterio/kanister/blob/b5613035af99b47ac277220fbadb7217c15a6af0/pkg/param/render.go#L123-L127) skips all jsonpath-looking string found in the function arguments. 

I don't know what's a safe way to fix this, without the risk of regression. Is jsonpath in function args a common use case?

What I got so far is to parse the Go templates first. If there are parsing errors and the inputs are valid jsonpath, then skip the errors. But this means invalid sub-keys within `TemplateParams` (e.g., `Object.foo.bar`) will also be treated as jsonpath.

```diff
diff --git a/pkg/param/render.go b/pkg/param/render.go
index b86c1079..b35def5f 100644
--- a/pkg/param/render.go
+++ b/pkg/param/render.go
@@ -120,18 +120,18 @@ func RenderArtifacts(arts map[string]crv1alpha1.Artifact, tp TemplateParams) (ma
 }
 
 func renderStringArg(arg string, tp TemplateParams) (string, error) {
-	// skip render if contains jsonpath arg
-	matched := jsonpath.FindJsonpathArgs(arg)
-	if len(matched) != 0 {
-		return arg, nil
-	}
-
 	t, err := template.New("config").Option("missingkey=error").Funcs(sprig.TxtFuncMap()).Parse(arg)
 	if err != nil {
 		return "", errors.WithStack(err)
 	}
 	buf := bytes.NewBuffer(nil)
 	if err = t.Execute(buf, tp); err != nil {
+		// skip render if contains jsonpath arg
+		matched := jsonpath.FindJsonpathArgs(arg)
+		if len(matched) != 0 {
+			return arg, nil
+		}
+
 		// Check if Error is because of undefined key,
 		// which will lead on execute error on first undefined (missingkey=error).
 		// Get the undefined key name from the error message.
```

**Comment by michaelcourcy** [comment]
I don't understand why if a string contains a jsonpath we just return the string instead of trying to render it. I probably miss something here.

**Comment by ihcsim** [comment]
Jsonpath is skipped so that they can be passed to the underlying command (e.g., `kubectl`) as-is, and let the tool handle them.

**Comment by michaelcourcy** [comment]
I see for instance the wait function https://docs.kanister.io/functions.html#wait can work with jsonpath 
```
- func: Wait
  name: waitNsReady
  args:
    timeout: 60s
    conditions:
      allOf:
        - condition: '{{ if (eq "{ $.status.phase }" "Invalid")}}true{{ else }}false{{ end }}'
          objectReference:
            apiVersion: v1
            resource: namespaces
            name: "{{ .Namespace.Name }}"
        - condition: '{{ if (eq "{ $.status.phase }" "Active")}}true{{ else }}false{{ end }}'
          objectReference:
            apiVersion: v1
            resource: namespaces
            name: "{{ .Namespace.Name }}"
```

This wait example is indeed a case where we must not render the template because `kubectl wait` is expecting a valid jsonpath.

Would it make sense to let the template author control if he wants the template to be rendered before being passed to the function.

For instance let's say that 3 single quote should not be rendered before being passed to the function ? 
```
'''{{ if (eq "{ $.status.phase }" "Invalid")}}true{{ else }}false{{ end }}'''
```

But 1 double or single quote should be rendered 
```
"{{ .Namespace.Name }}"
```

Another approach is to distinguish per function when to render and when we should not, it's harder to implement and maintain but more backward compatible with all the template that already use wait.
