### ISSUE TITLE
Please add an example ActionSet with Profile field

### ISSUE THREAD

**Issue by depohmel** [kanisterio/kanister#156]
I didn't find any documentation with an example of ActionSet with Profile. 
Took some time to find that Profile needs to be specified per each action, and it's a k8s object reference like this one. 
```
spec:
  actions:
  - name: backup
    blueprint: test-bp
    object:
      kind: Deployment
      name: my-test
      namespace: default
    profile:
      name: default-profile
      namespace: kanister
```
