### ISSUE TITLE
Wait function condition arg should only use go-template an not a mix of jsonpath and go-template 

### ISSUE THREAD

**Issue by michaelcourcy** [kanisterio/kanister#1583]
Today this usage of the [Wait](https://docs.kanister.io/functions.html#wait) function that seems natural does not work
```
- func: Wait
      name: waitCouchbaseClusterReadyAndBalanced
      args:
        timeout: 240s
        conditions:
          allOf:
            - condition: '{{ $available := false }}{{ range $condition := $.status.conditions }}{{ if and (eq .reason "Available") (eq .status "True")  }}{{ $available = true }}{{ end }}{{ end }}{{ $available }}'
              objectReference:
                apiVersion: couchbase.com/v2
                resource: couchbaseclusters
                name: "{{ .Object.metadata.name }}"
                namespace: "{{ .Object.metadata.namespace}}"
            - condition: '{{ $available := false }}{{ range $condition := $.status.conditions }}{{ if and (eq .reason "Balanced") (eq .status "True")  }}{{ $available = true }}{{ end }}{{ end }}{{ $available }}'
              objectReference:
                apiVersion: couchbase.com/v2
                resource: couchbaseclusters
                name: "{{ .Object.metadata.name }}"
                namespace: "{{ .Object.metadata.namespace}}"
```

Because the template has different level of rendering and at some point expression like `$.status.conditions` are evaluated as jsonpath. This is confusing and should be simplified.

**Describe the solution you'd like**
if `kubecl get -o go-template ...` evaluate as true for instance 
```
k get couchbaseclusters.couchbase.com cb-example -o go-template='{{ $available := false }}{{ range $condition := $.status.conditions }}{{ if and (eq .reason "Available") (eq .status "True")  }}{{ $available = true }}{{ end }}{{ end }}{{ $available }}'
true
```

Then the conditions  
```
            - condition: '{{ $available := false }}{{ range $condition := $.status.conditions }}{{ if and (eq .reason "Available") (eq .status "True")  }}{{ $available = true }}{{ end }}{{ end }}{{ $available }}'
```

should render and evaluate to true also.

**Describe alternatives you've considered**
For the moment the workaround we found is this construct 
```
            - condition: '{{ if (eq "{$.status.conditions[?(@.reason=="Available")].status}" "True") }}true{{ else }}false{{ end }}'            
              objectReference:
                apiVersion: v2
                group: couchbase.com
                resource: couchbaseclusters
                name: "{{ .Object.metadata.name }}"
                namespace: "{{ .Object.metadata.namespace}}"   
```

But this part `$.status.conditions[?(@.reason=="Available")].status` is not supported by go-template because it's a jsonpath, hence it's impossible to test your expression before you launch the actionset. There is no template engine that work with this mix.

One have to know when go-template stop and when jsonpath start it's pretty tricky.

**Environment**
Kubernetes Version/Provider: 1.22
Storage Provider: azure
Cluster Size (#nodes): 3
Data Size: 20Gb

**Additional context**
Kanister version 0.80.0

**Comment by michaelcourcy** [comment]
related also to https://github.com/kanisterio/kanister/issues/1470

**Comment by PrasadG193** [comment]
Thanks for raising this @michaelcourcy. I agree with you, the current syntax is a bit confusing. We definitely need to think how we can make it easier to understand and write one for BP authors.

**Comment by ihcsim** [comment]
Can we refactor `condition` to follow K8s `matchExpression` style? E.g., 

```yaml
conditions: 
-  key: "status.conditions.reason"
   operator: In
   values: ["Available"]
-  key: "status.conditions.type"
   operator: In
   values: ["Available"]
objectReference:
  apiVersion: v2
  group: couchbase.com
  resource: couchbaseclusters
  name: "{{ .Object.metadata.name }}"
  namespace: "{{ .Object.metadata.namespace}}" 
```

Then `conditions` will be evaluated to `true `if `objectReference` has all the `key`s with their values satisfying `values`.

I rather blueprint authors not have to worry about `if`, `range`, `$` etc. while working with `Wait`.

**Comment by michaelcourcy** [comment]
In the couchbase `conditions` status field is not a map but an array and we look for 2 elements in this array, one that have 
```
reason==Available && status==true 
```
And anonther one that have 
```
reason==Balanced && status==true 
```

Something like that should be possible to address this use case
```
conditions: 
-  key: "status.conditions[?(@.reason=="Available")].status"
   operator: In
   values: ["True"]
-  key: "status.conditions[?(@.reason=="Balanced")].status"
   operator: In
   values: ["True"]
```
