### ISSUE TITLE
[BUG] Blueprints are not editable/creatable due to failing to call webhook

### ISSUE THREAD

**Issue by GeekYiwen** [kanisterio/kanister#2120]
**Describe the bug**
When deploying Kanister using Helm releases created and managed by Helmfile (https://github.com/helmfile/helmfile) all interactions with the blueprints are failing due to failed calling of the webhook.

```
error: blueprints.cr.kanister.io "postgres-bp" could not be patched: Internal error occurred: failed calling webhook "blueprints.cr.kanister.io": failed to call webhook: Post "https://kanister-kanister-operator.kanister.svc:443/validate/v1alpha1/blueprint?timeout=5s": context deadline exceeded
You can run `kubectl replace -f /var/folders/m0/0lsgc8_94jg0zgdflnxwzzpm0000gp/T/kubectl-edit-1142251354.yaml` to try this update again.
```
This error occurs when creating or editing any blueprints after Kanister is deployed by Helm. I used the postgres example blueprint (changed some naming but should not be the issue here). 

Note: that installing the blueprints alongside Kanister both using helm releases works. Adding or changing any blueprints at a later point fails again due to the same error. This means that when I need to edit or create a blueprint I need to restart the whole Kanister stack to deploy a change to my blueprint.

I am not quite sure what to do here. Thanks in advance for any suggestions. If you are missing any information about this please let me know. 

**To Reproduce**
Apply helmfile with the following release:
#### helmfile.yaml
```
repositories:
  - name: kanister
    url: https://charts.kanister.io/

releases:
  - name: kanister
    namespace: kanister
    chart: kanister/kanister-operator
    version: 0.92.0
    labels:
      app: kanister-operator
      test: test
      dependency: operator
```

**Expected behavior**
Blueprints should be mutable and creatable after having a Kanister helm release in place.

**Environment**
helm version: v3.12.1
helmfile version: v0.154.0
kanister version: 0.92.0
