### ISSUE TITLE
[BUG] kando not restoring original files when passing file-path

### ISSUE THREAD

**Issue by r4rajat** [kanisterio/kanister#2230]
**Describe the bug**
While running `kando location pull` with filePath as target directory instead of stdin, kando is pulling kopia root entry for the file

**To Reproduce**
1) Install Kanister on supported k8s cluster

2) Create a Kopia based Profile

3) Deploy MySQL using helm
```
helm install mysql-release bitnami/mysql --namespace mysql-test \
--set auth.rootPassword='testPassword1234' \
--create-namespace
```

4) Create a Test Blueprint
```
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: mysql-blueprint
actions:
  backup:
    outputArtifacts:
      mysqlBackup:
        # Capture the kopia snapshot information for subsequent actions
        # The information includes the kopia snapshot ID which is essential for restore and delete to succeed
        # `kopiaOutput` is the name provided to kando using `--output-name` flag
        kopiaSnapshot: "{{ .Phases.dumpToStore.Output.kopiaOutput }}"
    phases:
      - func: KubeTask
        name: dumpToStore
        objects:
          mysqlSecret:
            kind: Secret
            name: '{{ index .Object.metadata.labels "app.kubernetes.io/instance" }}'
            namespace: '{{ .StatefulSet.Namespace }}'
        args:
          image: ghcr.io/kanisterio/mysql-sidecar:0.93.0
          namespace: "{{ .StatefulSet.Namespace }}"
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              mkdir -p /testdir/
              touch /testdir/test.txt
              echo "Testing Data" >> /testdir/test.txt
              kando location push --profile '{{ toJson .Profile }}' --output-name "kopiaOutput" /testdir/ 
  restore:
    inputArtifactNames:
      # The kopia snapshot info created in backup phase can be used here
      # Use the `--kopia-snapshot` flag in kando to pass in `mysqlBackup.KopiaSnapshot`
      - mysqlBackup
    phases:
      - func: KubeTask
        name: restoreFromStore
        objects:
          mysqlSecret:
            kind: Secret
            name: '{{ index .Object.metadata.labels "app.kubernetes.io/instance" }}'
            namespace: '{{ .StatefulSet.Namespace }}'
        args:
          image: ghcr.io/kanisterio/mysql-sidecar:0.93.0
          namespace: "{{ .StatefulSet.Namespace }}"
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              mkdir -p /testdir/
              kopia_snap='{{ .ArtifactsIn.mysqlBackup.KopiaSnapshot }}'
              kando location pull --profile '{{ toJson .Profile }}' --kopia-snapshot "${kopia_snap}" /testdir/
              sleep 10m
```
```
kubectl create -f test-blueprint.yaml -n kanister
```

5) Take Backup
```
kanctl create actionset --action backup --namespace kanister --blueprint mysql-blueprint --statefulset mysql-test/mysql-release --secrets mysql=mysql-test/mysql-release --profile=kanister/kopia-profile
```

6) Run Restore Action
```
kanctl --namespace kanister  create actionset --action restore --from "backup-kj9qp"
```

Restore action will wait for 10 minutes before completion, exec into the kanister-job-pod in `mysql-test` namespace and check the contents of `/testdir/` folder. 

**Expected behavior**
Upon looking for the contents of `/testdir/` folder, we find out that instead of `test.txt` we get `test.txt.kopia-entry` file.

**Screenshots**

**Environment**
Kubernetes Version/Provider: ...
Storage Provider: ...
Cluster Size (#nodes): ...
Data Size: ...

**Additional context**
