### ISSUE TITLE
[BUG] Support multiple runningPhases in actionset status

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#2270]
**Describe the bug**

ActionSet supports specifying multiple actions. When multiple actions are triggered using a single actionset, Kanister executes them in parallel. The ActionSet resource status has [runningPhase](https://github.com/kanisterio/kanister/blob/master/pkg/apis/cr/v1alpha1/types.go#L153) field which specifies the current running phase - which cannot show multiple phases if running in parallel. The type needs to be updated to show multiple phases in the execution

**To Reproduce**

1. Create a BP with multiple actions
2. Run 2 or more actions using actionset
    ```
    apiVersion: cr.kanister.io/v1alpha1
    kind: ActionSet
    metadata:
      name: test
      namespace: kanister
    spec:
      actions:
      - blueprint: example-bp
        name: action1
        object:
          kind: statefulset
          name: mysql
          namespace: mysql
      - blueprint: example-bp
        name: action2
        object:
          kind: statefulset
          name: mysql
          namespace: mysql
    ```

**Expected behavior**

The actionset status should show multiple phase names if they are in execution
