### ISSUE TITLE
CopyVolumeData followed by RestoreData does not restore to the original location

### ISSUE THREAD

**Issue by laurentiusoica** [kanisterio/kanister#2444]
For a single node PostgreSQL deployment with the Bitnami charts:
```
helm install postgresql --namespace postgresql bitnami/postgresql -f values.yaml --create-namespace
```
with this backup phase:
```
    - func: CopyVolumeData
      name: CopyPostgreSQLVolumeDataToObjectStore
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        volume: "data-postgresql-0"
        dataArtifactPrefix: indigo/postgresql/{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time | date "20060102150405" }}
```
and this restore phase:
```
    - func: RestoreData
      name: Restore Data From Object Store
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        image: ghcr.io/kanisterio/kanister-tools:0.98.0
        backupArtifactPrefix: "{{ .ArtifactsIn.backup.KeyValue.backupArtifactLocation }}"
        backupTag: "{{ .ArtifactsIn.backup.KeyValue.backupTag }}"
        volumes:
          data-postgresql-0: /bitnami/postgresql
        restorePath: /bitnami/postgresql
```

The data is restored under /mnt/vol_data/data-postgresql-0/ instead of the root of the volume.
