### ISSUE TITLE
Kanister-tools v0.99 binaries not working in Alpine Linux

### ISSUE THREAD

**Issue by brandtwinchell** [kanisterio/kanister#2481]
**Describe the bug**
When attempting to include/embed Kanister-tools (kanctl & kando) into an Alpine Linux Docker image, no installation errors but binaries cannot launch.

**To Reproduce**
1. Build image (see Docker file below)
2. Deploy pod (see pod manifest below)
3. Exec into pod ```kubectl exec -it -n default pods/devops-test-pod-kanister -- /bin/sh```
4. Verify kanister files exist and are executable ```ls -lah /usr/local/bin/```
5. Run kando help ```/usr/local/bin/kando --help```
6. ERROR: 'kando: not found'

**Expected behavior**
Binary should launch and return help notes.

**Environment**
Kubernetes Version/Provider: kubeadm v1.26.5
Storage Provider: Rook-Ceph
Cluster Size (#nodes): 9
Kasten: v6.0.11

**Additional context**
1. Confirmed running the [tools-install](https://docs.kanister.io/tooling.html#install-the-tools) while in a Ubuntu Docker image works as expected.

**Files**
Alpine Docker file:
``` yaml
# Stage 1: Build environment
FROM alpine as builder

RUN apk add --no-cache curl git bash perl

# Install Kanister Tools
RUN curl https://raw.githubusercontent.com/kanisterio/kanister/master/scripts/get.sh | bash

# Stage 2: Final image
FROM alpine

# Copy necessary binaries from the build environment
COPY --from=builder /usr/local/bin/kando /usr/local/bin/kando
COPY --from=builder /usr/local/bin/kanctl /usr/local/bin/kanctl
```

Ubuntu Docker file:
``` yaml
# Stage 1: Build environment
FROM ubuntu as builder

RUN apt update

RUN apt install bash git curl wget libdigest-sha-perl -y

# Install Kanister Tools
RUN curl https://raw.githubusercontent.com/kanisterio/kanister/master/scripts/get.sh | bash

# Stage 2: Final image
FROM ubuntu

# Copy necessary binaries from the build environment
COPY --from=builder /usr/local/bin/kando /usr/local/bin/kando
COPY --from=builder /usr/local/bin/kanctl /usr/local/bin/kanctl
```

Pod manifest file:
``` yaml
# Used for any ephemeral K8s pod testing
---
apiVersion: v1
kind: Pod
metadata:
  name: devops-test-pod-kanister
  namespace: default
spec:
  serviceAccountName: sa-kanister-bp-rabbit
  imagePullSecrets:
    - name: <git secret>
  containers:
  - name: worker
    #image: alpine/k8s1.28.0
    image: <private image registry>
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "infinity"
    resources:
      limits:
        cpu: "300m"
        memory: 512Mi
      requests:
        cpu: "50m"
        memory: 100Mi
  restartPolicy: Always
...
```
