### ISSUE TITLE
Enforce Installation of the Operator on stateless Nodepools

### ISSUE THREAD

**Issue by GeekYiwen** [kanisterio/kanister#2707]
**Is your feature request related to a problem? Please describe.**
As Kanister is a stateless operator I would like to enforce that Kanister will be running on a stateless nodepool. Many other K8s operators allow the option to specify `nodeSelector` and `tolerations` in the values file to enforce this.

**Describe the solution you'd like**
Add the possibility to enforce the installation of the Kanister operator on a stateless nodepool. This should be done by passing values in the helm chart.

**Example Values**
```
nodeSelector:
  node_pool: "stateless"

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "stateless"
    effect: "NoSchedule"
```
