### ISSUE TITLE
Add a patch operation to the Kubeops function

### ISSUE THREAD

**Issue by michaelcourcy** [kanisterio/kanister#2756]
**Is your feature request related to a problem? Please describe.**
Kubeops is great for creating or deleting resource, but sometime you just need to patch a resource, that goes from adding annotations to adding a complete spec tree. 

**Describe the solution you'd like**
Here is an example of a kubeops patch operation adding a backup section to a CNPG cluster 

```
- func: KubeOps
  name: addBackupSection
  object: 
  args:
    operation: patch
    objectReference:
      apiVersion: v1
      group: postgresql.cnpg.io
      resource: clusters
      name: "{{ .Object.metatada.name }}"
      namespace: "{{ .Object.metatada.namespace }}"    
    spec: |-
      spec:
          backup:
            barmanObjectStore:
              wal:
                compression: gzip
                encryption: AES256
              destinationPath: s3://{{ .Profile.Location.Bucket }}/{{ .Profile.Location.Prefix  }}/cnpg"
              s3Credentials:
                accessKeyId:
                  name: {{ .Profile.Credential.Secret.Name }}
                  key: aws_access_key_id
                secretAccessKey:
                  name: {{ .Profile.Credential.Secret.Name }}
                  key: aws_secret_access_key
```

**Describe alternatives you've considered**
Doing that wit a kubetask bash script that embed kubectl 

**Environment**
Kubernetes Version/Provider: ...
Storage Provider: ...
Cluster Size (#nodes): ...
Data Size: ...

**Additional context**
