### ISSUE TITLE
[Blueprint] read metadata from other kubernetes resources than secrets or configmaps

### ISSUE THREAD

**Issue by sybernatus** [kanisterio/kanister#2834]
**Is your feature request related to a problem? Please describe.**
It's more a question than a feature request
In Blueprint templates, I'm using objects field to access secrets data within my backup phase. As objects seems to be generic, I'm wondering if I can use it to access other kubernetes object data.

**Describe the solution you'd like**
I'd like to do something like this: 
```yaml
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: my-kasten-profile
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    credential:
      secret:
        apiVersion: v1
        kind: secret
        name: my-secret
        namespace: kasten-io
      secretType: AwsAccessKey
    objectStore:
      endpoint: https://my-s3-endpoint.com:10443
      name: my-s3
      objectStoreType: S3
      pathType: Directory
      region: fr-south-1
    type: ObjectStore
---

apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: my-backup
actions:
  backup:
    phases:
      - func: KubeExec
        name: backupToS3
        objects:
          s3Secret:
            kind: Secret
            name: 'my-secret'
            namespace: 'kasten-io'
          s3Location:
            group: config.kio.kasten.io
            kind: Profile <== Access other resources than secrets
            namespace: 'kasten-io'
            name: 'my-kasten-profile'
        args:
          namespace: "{{ .StatefulSet.Namespace }}"
          pod: "{{ index .StatefulSet.Pods 0 }}"
          container: my-container
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              S3_ACCESS_KEY={{ index .Phases.backupToS3.Secrets.s3Secret.Data "aws_access_key_id" | toString }} # <== This is working
              S3_LOCATION={{ index .Phases.backupToS3.Profile.s3Location.Data "endpoint" | toString }} # <== This is not working
```

**Environment**
Kubernetes Version/Provider: 1.25
Cluster Size (#nodes): 30
