### ISSUE TITLE
Enable linters for test packages

### ISSUE THREAD

**Issue by saima-s** [kanisterio/kanister#2962]
**Is your feature request related to a problem? Please describe.**
As of now linters are disabled from test packages in .golangci.yaml file:
```
issues:
  exclude-rules:
    - path: '_test.go'
      linters:
        - errcheck                      # Errors may be ignored in tests.
        - unparam                       # Tests might have unused function parameters.
        - lll
        - dupl
        - misspell
        - nestif
        - gci
```
**Describe the solution you'd like**
After enabling this linter, fix all kind of linter issues coming up in test packages.
