### ISSUE TITLE
[BUG] Failure reasons are no longer included in ActionSet error messages in 0.113.0

### ISSUE THREAD

**Issue by awbisschop** [kanisterio/kanister#3417]
**Describe the bug**
In version 0.109.0, if an action within an ActionSet would fail, the final line of the pod's log would be included in the Error.Message on the ActionSet.
In 0.113.0, it appears this is no longer the case.

**To Reproduce**
Using Kanister 0.113.0, use the following blueprint, deployment and actionset.
Create the deployment in the default namespace.
Create the blueprint and the actionset in the namespace in which Kanister is deployed.

_Blueprint_
```
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: test-blueprint
actions:
  backup:
    kind: Deployment
    inputArtifactNames:
      - backupset
    phases:
      - func: KubeTask
        name: backupFiles
        args:
          image: ghcr.io/kanisterio/kanister-kubectl-1.18:0.90.0
          namespace: backup
          command:
            - exit 1
``` 
Note: The command in the action is incorrect because "exit" is not a valid command. This is intentional.

_Deployment_
(Originates from the [tutorial](https://docs.kanister.io/tutorial.html))
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-logger
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: time-logger
  template:
    metadata:
      labels:
        app: time-logger
    spec:
      containers:
      - name: test-container
        image: containerlabs/aws-sdk
        command: ["sh", "-c"]
        args: ["while true; do for x in $(seq 1200); do date >> /var/log/time.log; sleep 1; done; truncate /var/log/time.log --size 0; done"]
``` 

_ActionSet_
```
apiVersion: cr.kanister.io/v1alpha1
kind: ActionSet
metadata:
  generateName: test-actionset-
spec:
  actions:
    - name: backup
      blueprint: test-blueprint
      object:
        kind: Deployment
        name: time-logger
        namespace: default
``` 

Describe the actionset. Note the following value for the Status.Error.Message property:

_Failed while waiting for Pod to complete: Pod failed to complete in time: Pod failed or did not transition into complete state: : Pod failed_

**Expected behavior**
I would expect the error logged by the generated pod to be included in the Status.Error.Message property in the ActionSet. As generated pods are automatically deleted, and no identifier for the pod is included in the error message, it is not possible to debug the failure.

Repeating the above steps with version 0.109.0 of Kanister, the end result is the following message:

_Failed while waiting for Pod kanister-job-kf2s8 to complete: Pod failed to complete in time: Pod failed or did not transition into complete state: : Pod kanister-job-kf2s8 failed. Pod status: &PodStatus{Phase:Failed,Conditions:[]PodCondition{PodCondition{Type:PodReadyToStartContainers,Status:False,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-03-24 13:48:54 +0000 UTC,Reason:,Message:,},PodCondition{Type:Initialized,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-03-24 13:48:46 +0000 UTC,Reason:,Message:,},PodCondition{Type:Ready,Status:False,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-03-24 13:48:46 +0000 UTC,Reason:PodFailed,Message:,},PodCondition{Type:ContainersReady,Status:False,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-03-24 13:48:46 +0000 UTC,Reason:PodFailed,Message:,},PodCondition{Type:PodScheduled,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-03-24 13:48:46 +0000 UTC,Reason:,Message:,},},Message:,Reason:,HostIP:172.23.0.2,PodIP:10.42.0.34,StartTime:2025-03-24 13:48:46 +0000 UTC,ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:container,State:ContainerState{Waiting:nil,Running:nil,Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:StartError,Message:**failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "exit 1": executable file not found in $PATH: unknown**,StartedAt:1970-01-01 00:00:00 +0000 UTC,FinishedAt:2025-03-24 13:48:53 +0000 UTC,ContainerID:containerd://9c94ce9d8e133fa8c4c3f2d7607dcaabf33363350d9f43da5f1ba636d7fff78e,},},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:false,RestartCount:0,Image:ghcr.io/kanisterio/kanister-kubectl-1.18:0.90.0,ImageID:ghcr.io/kanisterio/kanister-kubectl-1.18@sha256:0221f7e48bad42e274ae5e8d6a15c1a0846b315ed511d5518cd3a6109d2d8aba,ContainerID:containerd://9c94ce9d8e133fa8c4c3f2d7607dcaabf33363350d9f43da5f1ba636d7fff78e,Started:*false,AllocatedResources:ResourceList{},Resources:nil,},},QOSClass:BestEffort,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{PodIP{IP:10.42.0.34,},},EphemeralContainerStatuses:[]ContainerStatus{},Resize:,ResourceClaimStatuses:[]PodResourceClaimStatus{},HostIPs:[]HostIP{HostIP{IP:172.23.0.2,},},}_

The part in bold is the logging from the pod, and is very useful to determine the failure reason. This information is lost in version 0.113.0.

**Environment**
Kubernetes Version/Provider: v1.29.6 using k3s
Cluster Size (#nodes): Single Node

**Additional context**
From looking at the code changes, this issue may be present since 0.110.0, as the part of the code responsible for waiting for Pod completion was then updated to use errkit.
With errkit it appears that details, such as pod name and the last log line from the generated pod, are included as "extra details".
These extra details are not included in the Status.Error.Message property of the ActionSet.

**Comment by alka-infracloud** [comment]
@hairyhum @awbisschop I tried following case:- 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-logger-valid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-logger-valid
  template:
    metadata:
      labels:
        app: time-logger-valid
    spec:
      containers:
      - name: test-container
        image: ghcr.io/kanisterio/kanister-tools:0.113.0
        command: ["sh", "-c"]
        args: ["while true; do for x in $(seq 1200); do date >> /var/log/time.log; sleep 1; done; truncate /var/log/time.log --size 0; done"]
---
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: time-log-bp
  namespace: kanister
actions:
  backup:
    phases:
    - func: KubeExec
      name: backupToS3
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: test-container
        command:
          - exit 1
---
apiVersion: cr.kanister.io/v1alpha1
kind: ActionSet
metadata:
  generateName: s3backup-
  namespace: kanister
spec:
  actions:
  - name: backup
    blueprint: time-log-bp
    object:
      kind: Deployment
      name: time-logger-valid
      namespace: default         
```

2. Using kanister version 0.113.0
```
k get deployment -n kanister             kanister-kanister-operator -o yaml | grep image
        image: ghcr.io/kanisterio/controller:0.113.0
```

3. Kanister pod logs:- 
```
{"ActionSet":"s3backup-285hq","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdate","Line":184,"Status":"failed","hostname":"kanister-kanister-operator-6455988fb6-896b7","level":"info","msg":"Updated ActionSet","time":"2025-04-14T09:21:13.669486393Z"}
{"ActionSet":"s3backup-285hq","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1","Line":548,"Phase":"backupToS3","error":"Failed to exec command in pod: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec \"4c7aeb2463ed4c513fa25e71f5f695b2e4d74c35ad4f4cb0536e17368283433c\": OCI runtime exec failed: exec failed: unable to start container process: exec: \"exit 1\": executable file not found in $PATH.\nstdout: \nstderr: ","hostname":"kanister-kanister-operator-6455988fb6-896b7","level":"info","msg":"Failed to execute phase: v1alpha1.Phase{Name:\"backupToS3\", State:\"pending\", Output:map[string]interface {}(nil), Progress:v1alpha1.PhaseProgress{ProgressPercent:\"\", SizeDownloadedB:0, SizeUploadedB:0, EstimatedDownloadSizeB:0, EstimatedUploadSizeB:0, EstimatedTimeSeconds:0, LastTransitionTime:\u003cnil\u003e}}:","time":"2025-04-14T09:21:13.669547358Z"}
```

4. Status of actionset:-
```
k get actionset -n kanister    s3backup-285hq -o yaml
status:
  actions:
  - blueprint: time-log-bp
    deferPhase:
      name: ""
      progress: {}
      state: ""
    name: backup
    object:
      apiVersion: ""
      group: ""
      kind: Deployment
      name: time-logger-valid
      namespace: default
      resource: ""
    phases:
    - name: backupToS3
      progress: {}
      state: failed
  error:
    message: "Failed to exec command in pod: Internal error occurred: error executing
      command in container: failed to exec in container: failed to start exec \"4c7aeb2463ed4c513fa25e71f5f695b2e4d74c35ad4f4cb0536e17368283433c\":
      OCI runtime exec failed: exec failed: unable to start container process: exec:
      \"exit 1\": executable file not found in $PATH.\nstdout: \nstderr: "
  progress: {}
  state: failed
```

Conclusion:
In the actionset status I can see expected output. Let me know is there any other expectation here.
