### ISSUE TITLE
Allow users to configure the serviceAccountName for the kanister pods

### ISSUE THREAD

**Issue by alita1991** [kanisterio/kanister#3421]
**Is your feature request related to a problem? Please describe.**
I created a new blueprint that requires access to the K8s API to patch resources like ArgoCD, so I extended the Kanister operator's RBAC with additional roles. However, when executing the Kanister task in the application namespace, it defaults to using the standard service account.

https://github.com/kanisterio/kanister/blob/fa04d77eb6f5c92521d1413ddded385168f39f42/pkg/kube/pod.go#L79-L87

**Describe the solution you'd like**
The serviceAccountName field should be configurable (with this solution, an user can provision the required RBAC + serviceAccount)

**Environment**
Kubernetes Version/Provider: AWS EKS 1.31
Storage Provider: AWS EBS
Cluster Size (#nodes): 6 nodes (3 masters + 3 workers)
Data Size: 10Gi

**Additional context**
The default service account does not allow the users to perform the actions that the kanister operator service account can do.

**Comment by viveksinghggits** [comment]
This question is answered here in this slack thread https://cloud-native.slack.com/archives/C08J4RJC9HA/p1742927225143149?thread_ts=1742826287.333369&cid=C08J4RJC9HA


Like documented here (https://docs.kanister.io/functions.html#kubetask), the serviceAccount for the KubeTask pod can be configured using the function argument podOverride. Below is how it can be used
```
- func: KubeTask
  name: examplePhase
  args:
    namespace: "{{ .Deployment.Namespace }}"
    image: busybox
    podOverride:
      serviceAccountName: <serviceaccount-name>
      containers:
      - name: container
        imagePullPolicy: IfNotPresent
    podAnnotations:
      annKey: annValue
    podLabels:
      labelKey: labelValue
    command:
      - sh
      - -c
      - |
        echo "Example"
```
