### ISSUE TITLE
update postgresql-wale blueprint to refer the secret as an "Object" instead of reference name

### ISSUE THREAD

**Issue by rahulsidgondapatil** [kanisterio/kanister#561]
In postgresql blueprint we are referring the secret with name "postgresql" viz.:
``` 
secretNames:
- postgresql 
```
Objective of this task: 
Refer the secret as an "Object" instead of reference name viz:
```
      objects:
        postgresqlSecret:
          kind: Secret
          name: '{{ .StatefulSet.Name }}'
          namespace: '{{ .StatefulSet.Namespace }}'
```
