### ISSUE TITLE
[BUG] Failing to upload to minio object storage.

### ISSUE THREAD

**Issue by tellesnobrega** [kanisterio/kanister#682]
**Describe the bug**

I'm following the Kanister [tutorial](https://docs.kanister.io/tutorial.html#) but for some reason the endpoint is not being properly used on the cp command.

**To Reproduce**
1. Using minikube environment, install kanister and the time-log application as per [Kanister tutorial](https://docs.kanister.io/tutorial.html#)
2. Run the action set with [secrets](https://docs.kanister.io/tutorial.html#consuming-secrets)

The blueprint should look like this:
```
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: time-log-bp
  namespace: kanister
actions:
  backup:
    type: Deployment
    configMapNames:
    - location
    secretNames:
    - aws
    phases:
    - func: KubeExec
      name: backupToS3
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: test-container
        command:
          - sh
          - -c
          - |
            AWS_ACCESS_KEY_ID={{ .Secrets.aws.Data.aws_access_key_id | toString }}         \
            AWS_SECRET_ACCESS_KEY={{ .Secrets.aws.Data.aws_secret_access_key | toString }} \
            aws s3 cp /var/log/time.log {{ .ConfigMaps.location.Data.path | quote }}
```

The action set:

```
apiVersion: cr.kanister.io/v1alpha1
kind: ActionSet
metadata:
  generateName: s3backup-
  namespace: kanister
spec:
  actions:
  - name: backup
    blueprint: time-log-bp
    object:
      kind: Deployment
      name: time-logger
      namespace: default
    profile: 
      name: <your-profile>
      namespace: kanister
    configMaps:
          location:
            name: s3-location
            namespace: kanister
    secrets:
      aws:
        name: aws-creds
        namespace: kanister
```
The config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-location
  namespace: kanister
data:
  path: s3://kubedemo
  region: minio
```
And the secrets file:
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: kanister
type: Opaque
data:
  aws_access_key_id: <BASE64_AWS_ACCESS_KEY_ID>
  aws_secret_access_key: <BASE64_AWS_SECRET_ACCESS_KEY>
```
3. Check the logs of the controller and see that it failed to execute due to: Out="upload failed: var/log/time.log to s3://kubedemo/time.log An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.

**Expected behavior**
Backup created and file copied to the minio bucket.

**Workaround** 
If I add --endpoint <URL> to the end of the aws cp command the backup works. This makes me think that the endpoint on the profile is not being used properly.
